version: "3"

services:
  product-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=StockDB
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=root
    ports:
      - "3308:3306"
